import image_1 from './library_logo.jpg';
import iitdh_logo from './iitdh-logo.png';
import footer_image from './iitdh-footer.jpg';
import header_image from './landing-page-eLibrary.jpg';

export const assets={
    iitdh_logo,
    footer_image,
    header_image
}

export const category_list=[
    {
        category_name:"Engineering",
    },
    {
        category_name:"Science",
    },
    {
        category_name:"Technology and Applied Sciences",
    },
    {
        category_name:"Competitive Exams",
    },
    {
        category_name:"Business and Management",
    },
    {
      category_name:"Programming and Software Development",
  }
]

export const Engineering=[
    {
      department_name:"Computer Science",
    },
    {
      department_name:"Mechanical Engineering",
    },
    {
      department_name:"Electrical Engineering",
    },
    {
      department_name:"Civil Engineering",
    },
    {
      department_name:"Chemical Engineering",
    },
    {
      department_name:"Engineering Physics",
    }
]



export const books_data=[
  {
    "title": "Quantum Mechanics: Concepts and Applications",
    "description": "An introduction to quantum mechanics, covering fundamental concepts and applications.",
    "author": "Nouredine Zettili",
    "genre": "Physics",
    "department": "Science",
    "count": 10,
    "vendor": "Academic Press",
    "vendor_id": 1001,
    "publisher": "John Wiley & Sons",
    "publisher_id": 345671
  },
  {
    "title": "Classical Mechanics",
    "description": "A detailed study of classical mechanics, including the principles of motion.",
    "author": "Herbert Goldstein",
    "genre": "Physics",
    "department": "Science",
    "count": 10,
    "vendor": "Pearson",
    "vendor_id": 1002,
    "publisher": "Pearson Education",
    "publisher_id": 345672
  },
  {
    "title": "Introduction to Electrodynamics",
    "description": "A comprehensive guide to the principles of electrodynamics.",
    "author": "David J. Griffiths",
    "genre": "Physics",
    "department": "Science",
    "count": 10,
    "vendor": "Cambridge University Press",
    "vendor_id": 1003,
    "publisher": "Cambridge University Press",
    "publisher_id": 345673
  },
  {
    "title": "Thermodynamics: An Engineering Approach",
    "description": "An engineering perspective on the principles of thermodynamics.",
    "author": "Yunus A. Cengel, Michael A. Boles",
    "genre": "Physics",
    "department": "Science",
    "count": 10,
    "vendor": "McGraw-Hill",
    "vendor_id": 1004,
    "publisher": "McGraw-Hill Education",
    "publisher_id": 345674
  },
  {
    "title": "Optics",
    "description": "A comprehensive introduction to the principles of optics.",
    "author": "Eugene Hecht",
    "genre": "Physics",
    "department": "Science",
    "count": 10,
    "vendor": "Addison-Wesley",
    "vendor_id": 1005,
    "publisher": "Addison-Wesley",
    "publisher_id": 345675
  },
  {
    "title": "Physics for Scientists and Engineers",
    "description": "A textbook for scientists and engineers covering fundamental physics principles.",
    "author": "Raymond A. Serway, John W. Jewett",
    "genre": "Physics",
    "department": "Science",
    "count": 10,
    "vendor": "Cengage Learning",
    "vendor_id": 1006,
    "publisher": "Cengage Learning",
    "publisher_id": 345676
  },
  {
    "title": "Modern Physics",
    "description": "An exploration of modern physics concepts.",
    "author": "Kenneth S. Krane",
    "genre": "Physics",
    "department": "Science",
    "count": 10,
    "vendor": "Wiley",
    "vendor_id": 1007,
    "publisher": "John Wiley & Sons",
    "publisher_id": 345677
  },
  {
    "title": "Nuclear Physics: Principles and Applications",
    "description": "A textbook on the principles and applications of nuclear physics.",
    "author": "John Lilley",
    "genre": "Physics",
    "department": "Science",
    "count": 10,
    "vendor": "Wiley",
    "vendor_id": 1008,
    "publisher": "John Wiley & Sons",
    "publisher_id": 345678
  },
  {
    "title": "Introduction to Solid State Physics",
    "description": "A detailed study of the principles of solid state physics.",
    "author": "Charles Kittel",
    "genre": "Physics",
    "department": "Science",
    "count": 10,
    "vendor": "Wiley",
    "vendor_id": 1009,
    "publisher": "John Wiley & Sons",
    "publisher_id": 345679
  },
  {
    "title": "Statistical Mechanics",
    "description": "An introduction to the principles of statistical mechanics.",
    "author": "R.K. Pathria, Paul D. Beale",
    "genre": "Physics",
    "department": "Science",
    "count": 10,
    "vendor": "Elsevier",
    "vendor_id": 1010,
    "publisher": "Elsevier",
    "publisher_id": 345680
  },
  {
    "title": "Organic Chemistry",
    "description": "A comprehensive guide to the principles and reactions of organic chemistry.",
    "author": "Paula Yurkanis Bruice",
    "genre": "Chemistry",
    "department": "Science",
    "count": 10,
    "vendor": "Pearson",
    "vendor_id": 1002,
    "publisher": "Pearson Education",
    "publisher_id": 345681
  },
  {
    "title": "Inorganic Chemistry",
    "description": "An introduction to the principles and applications of inorganic chemistry.",
    "author": "Gary L. Miessler, Paul J. Fischer, Donald A. Tarr",
    "genre": "Chemistry",
    "department": "Science",
    "count": 10,
    "vendor": "Pearson",
    "vendor_id": 1002,
    "publisher": "Pearson Education",
    "publisher_id": 345682
  },
  {
    "title": "Physical Chemistry",
    "description": "A textbook on the principles of physical chemistry.",
    "author": "Peter Atkins, Julio de Paula",
    "genre": "Chemistry",
    "department": "Science",
    "count": 10,
    "vendor": "Oxford University Press",
    "vendor_id": 1011,
    "publisher": "Oxford University Press",
    "publisher_id": 345683
  },
  {
    "title": "Analytical Chemistry",
    "description": "An introduction to the techniques and applications of analytical chemistry.",
    "author": "Gary D. Christian",
    "genre": "Chemistry",
    "department": "Science",
    "count": 10,
    "vendor": "Wiley",
    "vendor_id": 1007,
    "publisher": "John Wiley & Sons",
    "publisher_id": 345684
  },
  {
    "title": "Biochemistry",
    "description": "A detailed study of the chemical processes within and related to living organisms.",
    "author": "Jeremy M. Berg, John L. Tymoczko, Lubert Stryer",
    "genre": "Chemistry",
    "department": "Science",
    "count": 10,
    "vendor": "W.H. Freeman",
    "vendor_id": 1012,
    "publisher": "W.H. Freeman",
    "publisher_id": 345685
  },
  {
    "title": "Quantum Chemistry",
    "description": "An introduction to the principles of quantum chemistry.",
    "author": "Ira N. Levine",
    "genre": "Chemistry",
    "department": "Science",
    "count": 10,
    "vendor": "Pearson",
    "vendor_id": 1002,
    "publisher": "Pearson Education",
    "publisher_id": 345686
  },
  {
    "title": "Chemistry: The Central Science",
    "description": "A comprehensive guide to the principles and applications of chemistry.",
    "author": "Theodore L. Brown, H. Eugene LeMay, Bruce E. Bursten",
    "genre": "Chemistry",
    "department": "Science",
    "count": 10,
    "vendor": "Pearson",
    "vendor_id": 1002,
    "publisher": "Pearson Education",
    "publisher_id": 345687
  },
  {
    "title": "Principles of Instrumental Analysis",
    "description": "An introduction to the techniques and applications of instrumental analysis.",
    "author": "Douglas A. Skoog, F. James Holler, Stanley R. Crouch",
    "genre": "Chemistry",
    "department": "Science",
    "count": 10,
    "vendor": "Cengage Learning",
    "vendor_id": 1006,
    "publisher": "Cengage Learning",
    "publisher_id": 345688
  },
  {
    "title": "Solid State Chemistry",
    "description": "A detailed study of the principles and applications of solid state chemistry.",
    "author": "Lesley E. Smart, Elaine A. Moore",
    "genre": "Chemistry",
    "department": "Science",
    "count": 10,
    "vendor": "CRC Press",
    "vendor_id": 1013,
    "publisher": "CRC Press",
    "publisher_id": 345689
  },
  {
    "title": "Environmental Chemistry",
    "description": "An introduction to the principles and applications of environmental chemistry.",
    "author": "Stanley E. Manahan",
    "genre": "Chemistry",
    "department": "Science",
    "count": 10,
    "vendor": "CRC Press",
    "vendor_id": 1013,
    "publisher": "CRC Press",
    "publisher_id": 345690
  },
  {
    "title": "Calculus: Early Transcendentals",
    "description": "A comprehensive guide to the principles and applications of calculus.",
    "author": "James Stewart",
    "genre": "Mathematics",
    "department": "Science",
    "count": 10,
    "vendor": "Cengage Learning",
    "vendor_id": 1006,
    "publisher": "Cengage Learning",
    "publisher_id": 345691
  },
  {
    "title": "Linear Algebra and Its Applications",
    "description": "An introduction to the principles and applications of linear algebra.",
    "author": "Gilbert Strang",
    "genre": "Mathematics",
    "department": "Science",
    "count": 10,
    "vendor": "Wellesley-Cambridge Press",
    "vendor_id": 1014,
    "publisher": "Wellesley-Cambridge Press",
    "publisher_id": 345692
  },
  {
    "title": "Discrete Mathematics and Its Applications",
    "description": "A comprehensive guide to the principles and applications of discrete mathematics.",
    "author": "Kenneth H. Rosen",
    "genre": "Mathematics",
    "department": "Science",
    "count": 10,
    "vendor": "McGraw-Hill",
    "vendor_id": 1004,
    "publisher": "McGraw-Hill Education",
    "publisher_id": 345693
  },
  {
    "title": "Introduction to Probability",
    "description": "An introduction to the principles of probability.",
    "author": "Dimitri P. Bertsekas, John N. Tsitsiklis",
    "genre": "Mathematics",
    "department": "Science",
    "count": 10,
    "vendor": "Athena Scientific",
    "vendor_id": 1015,
    "publisher": "Athena Scientific",
    "publisher_id": 345694
  },
  {
    "title": "Abstract Algebra",
    "description": "A detailed study of the principles of abstract algebra.",
    "author": "David S. Dummit, Richard M. Foote",
    "genre": "Mathematics",
    "department": "Science",
    "count": 10,
    "vendor": "Wiley",
    "vendor_id": 1007,
    "publisher": "John Wiley & Sons",
    "publisher_id": 345695
  },
  {
    "title": "Real Analysis",
    "description": "An introduction to the principles and applications of real analysis.",
    "author": "H.L. Royden, P.M. Fitzpatrick",
    "genre": "Mathematics",
    "department": "Science",
    "count": 10,
    "vendor": "Pearson",
    "vendor_id": 1002,
    "publisher": "Pearson Education",
    "publisher_id": 345696
  },
  {
    "title": "Complex Analysis",
    "description": "A comprehensive guide to the principles and applications of complex analysis.",
    "author": "Lars Ahlfors",
    "genre": "Mathematics",
    "department": "Science",
    "count": 10,
    "vendor": "McGraw-Hill",
    "vendor_id": 1004,
    "publisher": "McGraw-Hill Education",
    "publisher_id": 345697
  },
  {
    "title": "Numerical Analysis",
    "description": "An introduction to the principles and applications of numerical analysis.",
    "author": "Richard L. Burden, J. Douglas Faires",
    "genre": "Mathematics",
    "department": "Science",
    "count": 10,
    "vendor": "Cengage Learning",
    "vendor_id": 1006,
    "publisher": "Cengage Learning",
    "publisher_id": 345698
  },
  {
    "title": "Topology",
    "description": "A detailed study of the principles of topology.",
    "author": "James Munkres",
    "genre": "Mathematics",
    "department": "Science",
    "count": 10,
    "vendor": "Pearson",
    "vendor_id": 1002,
    "publisher": "Pearson Education",
    "publisher_id": 345699
  },
  {
    "title": "Mathematical Statistics with Applications",
    "description": "An introduction to the principles and applications of mathematical statistics.",
    "author": "Dennis Wackerly, William Mendenhall, Richard L. Scheaffer",
    "genre": "Mathematics",
    "department": "Science",
    "count": 10,
    "vendor": "Cengage Learning",
    "vendor_id": 1006,
    "publisher": "Cengage Learning",
    "publisher_id": 345700
  },
  {
    "title": "Molecular Biology of the Cell",
    "description": "A comprehensive guide to the principles of molecular biology.",
    "author": "Bruce Alberts, Alexander Johnson, Julian Lewis",
    "genre": "Biology",
    "department": "Science",
    "count": 10,
    "vendor": "Garland Science",
    "vendor_id": 1016,
    "publisher": "Garland Science",
    "publisher_id": 345701
  },
  {
    "title": "Principles of Genetics",
    "description": "An introduction to the principles of genetics.",
    "author": "D. Peter Snustad, Michael J. Simmons",
    "genre": "Biology",
    "department": "Science",
    "count": 10,
    "vendor": "Wiley",
    "vendor_id": 1007,
    "publisher": "John Wiley & Sons",
    "publisher_id": 345702
  },
  {
    "title": "Biology",
    "description": "A comprehensive guide to the principles and applications of biology.",
    "author": "Neil A. Campbell, Jane B. Reece",
    "genre": "Biology",
    "department": "Science",
    "count": 10,
    "vendor": "Pearson",
    "vendor_id": 1002,
    "publisher": "Pearson Education",
    "publisher_id": 345703
  },
  {
    "title": "Microbiology",
    "description": "An introduction to the principles and applications of microbiology.",
    "author": "Gerard J. Tortora, Berdell R. Funke, Christine L. Case",
    "genre": "Biology",
    "department": "Science",
    "count": 10,
    "vendor": "Pearson",
    "vendor_id": 1002,
    "publisher": "Pearson Education",
    "publisher_id": 345704
  },
  {
    "title": "Cell and Molecular Biology",
    "description": "A detailed study of the principles of cell and molecular biology.",
    "author": "Gerald Karp",
    "genre": "Biology",
    "department": "Science",
    "count": 10,
    "vendor": "Wiley",
    "vendor_id": 1007,
    "publisher": "John Wiley & Sons",
    "publisher_id": 345705
  },
  {
    "title": "Human Physiology",
    "description": "An introduction to the principles and applications of human physiology.",
    "author": "Stuart Ira Fox",
    "genre": "Biology",
    "department": "Science",
    "count": 10,
    "vendor": "McGraw-Hill",
    "vendor_id": 1004,
    "publisher": "McGraw-Hill Education",
    "publisher_id": 345706
  },
  {
    "title": "Developmental Biology",
    "description": "A comprehensive guide to the principles of developmental biology.",
    "author": "Scott F. Gilbert",
    "genre": "Biology",
    "department": "Science",
    "count": 10,
    "vendor": "Sinauer Associates",
    "vendor_id": 1017,
    "publisher": "Sinauer Associates",
    "publisher_id": 345707
  },
  {
    "title": "Ecology: Concepts and Applications",
    "description": "An introduction to the principles and applications of ecology.",
    "author": "Manuel C. Molles",
    "genre": "Biology",
    "department": "Science",
    "count": 10,
    "vendor": "McGraw-Hill",
    "vendor_id": 1004,
    "publisher": "McGraw-Hill Education",
    "publisher_id": 345708
  },
  {
    "title": "Genetics: Analysis and Principles",
    "description": "A detailed study of the principles and applications of genetics.",
    "author": "Robert J. Brooker",
    "genre": "Biology",
    "department": "Science",
    "count": 10,
    "vendor": "McGraw-Hill",
    "vendor_id": 1004,
    "publisher": "McGraw-Hill Education",
    "publisher_id": 345709
  },
  {
    "title": "Plant Biology",
    "description": "An introduction to the principles and applications of plant biology.",
    "author": "Linda E. Graham, James M. Graham, Lee W. Wilcox",
    "genre": "Biology",
    "department": "Science",
    "count": 10,
    "vendor": "Pearson",
    "vendor_id": 1002,
    "publisher": "Pearson Education",
    "publisher_id": 345710
  },
  {
    "title": "Information Technology Project Management",
    "description": "A comprehensive guide to project management in IT.",
    "author": "Kathy Schwalbe",
    "genre": "Information Technology",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Cengage Learning",
    "vendor_id": 1006,
    "publisher": "Cengage Learning",
    "publisher_id": 345711
  },
  {
    "title": "Introduction to Information Systems",
    "description": "An introductory text to information systems.",
    "author": "R. Kelly Rainer, Brad Prince",
    "genre": "Information Technology",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Wiley",
    "vendor_id": 1007,
    "publisher": "John Wiley & Sons",
    "publisher_id": 345712
  },
  {
    "title": "Management Information Systems",
    "description": "A study on the management of information systems.",
    "author": "Kenneth C. Laudon, Jane P. Laudon",
    "genre": "Information Technology",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Pearson",
    "vendor_id": 1002,
    "publisher": "Pearson Education",
    "publisher_id": 345713
  },
  {
    "title": "Information Technology for Management",
    "description": "Digital strategies for insights, action, and sustainable performance.",
    "author": "Efraim Turban, Linda Volonino",
    "genre": "Information Technology",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Wiley",
    "vendor_id": 1007,
    "publisher": "John Wiley & Sons",
    "publisher_id": 345714
  },
  {
    "title": "IT Strategy: Issues and Practices",
    "description": "An exploration of IT strategy and its implementation.",
    "author": "James D. McKeen, Heather A. Smith",
    "genre": "Information Technology",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Pearson",
    "vendor_id": 1002,
    "publisher": "Pearson Education",
    "publisher_id": 345715
  },
  {
    "title": "Information Systems Today",
    "description": "Managing the digital world.",
    "author": "Joseph Valacich, Christoph Schneider",
    "genre": "Information Technology",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Pearson",
    "vendor_id": 1002,
    "publisher": "Pearson Education",
    "publisher_id": 345716
  },
  {
    "title": "Business Driven Technology",
    "description": "A business-first approach to learning about technology.",
    "author": "Paige Baltzan",
    "genre": "Information Technology",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "McGraw-Hill",
    "vendor_id": 1004,
    "publisher": "McGraw-Hill Education",
    "publisher_id": 345717
  },
  {
    "title": "Principles of Information Systems",
    "description": "A comprehensive guide to information systems.",
    "author": "Ralph Stair, George Reynolds",
    "genre": "Information Technology",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Cengage Learning",
    "vendor_id": 1006,
    "publisher": "Cengage Learning",
    "publisher_id": 345718
  },
  {
    "title": "IT Governance: How Top Performers Manage IT Decision Rights for Superior Results",
    "description": "Strategies for managing IT governance.",
    "author": "Peter Weill, Jeanne W. Ross",
    "genre": "Information Technology",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Harvard Business Review Press",
    "vendor_id": 1018,
    "publisher": "Harvard Business Review Press",
    "publisher_id": 345719
  },
  {
    "title": "The Adventures of an IT Leader",
    "description": "A unique narrative exploring the role of the IT leader.",
    "author": "Robert D. Austin, Richard L. Nolan, Shannon O'Donnell",
    "genre": "Information Technology",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Harvard Business Review Press",
    "vendor_id": 1018,
    "publisher": "Harvard Business Review Press",
    "publisher_id": 345720
  },
  {
    "title": "Artificial Intelligence: A Modern Approach",
    "description": "Fundamental concepts and techniques in AI, covering a wide range of topics.",
    "author": "Stuart Russell, Peter Norvig",
    "genre": "Artificial Intelligence",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Pearson",
    "vendor_id": 1002,
    "publisher": "Pearson Education",
    "publisher_id": 345721
  },
  {
    "title": "Deep Learning",
    "description": "An introduction to deep learning.",
    "author": "Ian Goodfellow, Yoshua Bengio, Aaron Courville",
    "genre": "Artificial Intelligence",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "MIT Press",
    "vendor_id": 1019,
    "publisher": "MIT Press",
    "publisher_id": 345722
  },
  {
    "title": "Artificial Intelligence: Foundations of Computational Agents",
    "description": "A study on the foundations of AI agents.",
    "author": "David L. Poole, Alan K. Mackworth",
    "genre": "Artificial Intelligence",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Cambridge University Press",
    "vendor_id": 1020,
    "publisher": "Cambridge University Press",
    "publisher_id": 345723
  },
  {
    "title": "Machine Learning: A Probabilistic Perspective",
    "description": "An introduction to the principles of machine learning.",
    "author": "Kevin P. Murphy",
    "genre": "Artificial Intelligence",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "MIT Press",
    "vendor_id": 1019,
    "publisher": "MIT Press",
    "publisher_id": 345724
  },
  {
    "title": "Pattern Recognition and Machine Learning",
    "description": "An in-depth look at pattern recognition and machine learning.",
    "author": "Christopher M. Bishop",
    "genre": "Artificial Intelligence",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Springer",
    "vendor_id": 1021,
    "publisher": "Springer",
    "publisher_id": 345725
  },
  {
    "title": "AI: A Very Short Introduction",
    "description": "A brief overview of artificial intelligence.",
    "author": "Margaret A. Boden",
    "genre": "Artificial Intelligence",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Oxford University Press",
    "vendor_id": 1022,
    "publisher": "Oxford University Press",
    "publisher_id": 345726
  },
  {
    "title": "The Master Algorithm",
    "description": "An exploration of the quest for the ultimate learning machine.",
    "author": "Pedro Domingos",
    "genre": "Artificial Intelligence",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Basic Books",
    "vendor_id": 1023,
    "publisher": "Basic Books",
    "publisher_id": 345727
  },
  {
    "title": "Superintelligence: Paths, Dangers, Strategies",
    "description": "A discussion on the future of artificial intelligence and its potential impacts.",
    "author": "Nick Bostrom",
    "genre": "Artificial Intelligence",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Oxford University Press",
    "vendor_id": 1022,
    "publisher": "Oxford University Press",
    "publisher_id": 345728
  },
  {
    "title": "Life 3.0: Being Human in the Age of Artificial Intelligence",
    "description": "An examination of what the future might look like with advanced AI.",
    "author": "Max Tegmark",
    "genre": "Artificial Intelligence",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Knopf",
    "vendor_id": 1024,
    "publisher": "Knopf",
    "publisher_id": 345729
  },
  {
    "title": "Artificial Intelligence for Humans",
    "description": "An accessible guide to the fundamentals of AI.",
    "author": "Jeff Heaton",
    "genre": "Artificial Intelligence",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "CreateSpace",
    "vendor_id": 1025,
    "publisher": "CreateSpace Independent Publishing Platform",
    "publisher_id": 345730
  },
  {
    "title": "Data Science for Business",
    "description": "What you need to know about data mining and data-analytic thinking.",
    "author": "Foster Provost, Tom Fawcett",
    "genre": "Data Science",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "O'Reilly Media",
    "vendor_id": 1026,
    "publisher": "O'Reilly Media",
    "publisher_id": 345731
  },
  {
    "title": "Data Science from Scratch",
    "description": "First principles with Python.",
    "author": "Joel Grus",
    "genre": "Data Science",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "O'Reilly Media",
    "vendor_id": 1026,
    "publisher": "O'Reilly Media",
    "publisher_id": 345732
  },
  {
    "title": "Python Data Science Handbook",
    "description": "Essential tools for working with data in Python.",
    "author": "Jake VanderPlas",
    "genre": "Data Science",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "O'Reilly Media",
    "vendor_id": 1026,
    "publisher": "O'Reilly Media",
    "publisher_id": 345733
  },
  {
    "title": "Data Science and Big Data Analytics",
    "description": "Discovering, analyzing, visualizing and presenting data.",
    "author": "EMC Education Services",
    "genre": "Data Science",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Wiley",
    "vendor_id": 1007,
    "publisher": "John Wiley & Sons",
    "publisher_id": 345734
  },
  {
    "title": "Introduction to Data Mining",
    "description": "Introduction to data mining techniques and applications.",
    "author": "Pang-Ning Tan, Michael Steinbach, Vipin Kumar",
    "genre": "Data Science",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Pearson",
    "vendor_id": 1002,
    "publisher": "Pearson Education",
    "publisher_id": 345735
  },
  {
    "title": "Data Science for Dummies",
    "description": "An easy-to-understand introduction to data science.",
    "author": "Lillian Pierson",
    "genre": "Data Science",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Wiley",
    "vendor_id": 1007,
    "publisher": "John Wiley & Sons",
    "publisher_id": 345736
  },
  {
    "title": "Data Science on the Google Cloud Platform",
    "description": "A guide to data science using Google Cloud Platform.",
    "author": "Valliappa Lakshmanan",
    "genre": "Data Science",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "O'Reilly Media",
    "vendor_id": 1026,
    "publisher": "O'Reilly Media",
    "publisher_id": 345737
  },
  {
    "title": "Big Data: Principles and Best Practices of Scalable Real-Time Data Systems",
    "description": "Guidance on designing and implementing big data systems.",
    "author": "Nathan Marz, James Warren",
    "genre": "Data Science",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Manning Publications",
    "vendor_id": 1027,
    "publisher": "Manning Publications",
    "publisher_id": 345738
  },
  {
    "title": "Practical Statistics for Data Scientists",
    "description": "50 essential concepts for data science.",
    "author": "Peter Bruce, Andrew Bruce",
    "genre": "Data Science",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "O'Reilly Media",
    "vendor_id": 1026,
    "publisher": "O'Reilly Media",
    "publisher_id": 345739
  },
  {
    "title": "Data Science for Engineers",
    "description": "An introduction to data science techniques for engineers.",
    "author": "R. Madhavan",
    "genre": "Data Science",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Springer",
    "vendor_id": 1021,
    "publisher": "Springer",
    "publisher_id": 345740
  },
  {
    "title": "Cybersecurity Essentials",
    "description": "A comprehensive guide to the essentials of cybersecurity.",
    "author": "Charles J. Brooks, Christopher Grow, Philip Craig, Donald Short",
    "genre": "Cybersecurity",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Wiley",
    "vendor_id": 1007,
    "publisher": "John Wiley & Sons",
    "publisher_id": 345741
  },
  {
    "title": "The Art of Deception",
    "description": "An exploration of the human element in cybersecurity.",
    "author": "Kevin D. Mitnick, William L. Simon",
    "genre": "Cybersecurity",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Wiley",
    "vendor_id": 1007,
    "publisher": "John Wiley & Sons",
    "publisher_id": 345742
  },
  {
    "title": "Cybersecurity and Cyberwar",
    "description": "A look at what everyone needs to know about cybersecurity.",
    "author": "P.W. Singer, Allan Friedman",
    "genre": "Cybersecurity",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Oxford University Press",
    "vendor_id": 1022,
    "publisher": "Oxford University Press",
    "publisher_id": 345743
  },
  {
    "title": "Applied Cyber Security and the Smart Grid",
    "description": "Implementation of security in the smart grid environment.",
    "author": "Eric D. Knapp, Raj Samani",
    "genre": "Cybersecurity",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Elsevier",
    "vendor_id": 1028,
    "publisher": "Elsevier",
    "publisher_id": 345744
  },
  {
    "title": "Cybersecurity for Beginners",
    "description": "An introductory text to the field of cybersecurity.",
    "author": "Raef Meeuwisse",
    "genre": "Cybersecurity",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Cyber Simplicity Ltd",
    "vendor_id": 1029,
    "publisher": "Cyber Simplicity Ltd",
    "publisher_id": 345745
  },
  {
    "title": "Hacking: The Art of Exploitation",
    "description": "A detailed look at the art of hacking and exploitation.",
    "author": "Jon Erickson",
    "genre": "Cybersecurity",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "No Starch Press",
    "vendor_id": 1030,
    "publisher": "No Starch Press",
    "publisher_id": 345746
  },
  {
    "title": "Practical Malware Analysis",
    "description": "An in-depth guide to analyzing and understanding malware.",
    "author": "Michael Sikorski, Andrew Honig",
    "genre": "Cybersecurity",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "No Starch Press",
    "vendor_id": 1030,
    "publisher": "No Starch Press",
    "publisher_id": 345747
  },
  {
    "title": "Metasploit: The Penetration Tester's Guide",
    "description": "A guide to using Metasploit for penetration testing.",
    "author": "David Kennedy, Jim O'Gorman, Devon Kearns, Mati Aharoni",
    "genre": "Cybersecurity",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "No Starch Press",
    "vendor_id": 1030,
    "publisher": "No Starch Press",
    "publisher_id": 345748
  },
  {
    "title": "The Web Application Hacker's Handbook",
    "description": "A comprehensive guide to web application security.",
    "author": "Dafydd Stuttard, Marcus Pinto",
    "genre": "Cybersecurity",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Wiley",
    "vendor_id": 1007,
    "publisher": "John Wiley & Sons",
    "publisher_id": 345749
  },
  {
    "title": "Cybersecurity and Applied Mathematics",
    "description": "Mathematical concepts and techniques applied to cybersecurity.",
    "author": "Dr. Leigh Metcalf, Dr. William Casey",
    "genre": "Cybersecurity",
    "department": "Technology and Applied Sciences",
    "count": 10,
    "vendor": "Elsevier",
    "vendor_id": 1028,
    "publisher": "Elsevier",
    "publisher_id": 345750
  }
]
