import image_1 from './library_logo.jpg';
import iitdh_logo from './iitdh-logo.png';
import footer_image from './iitdh-footer.jpg';
import header_image from './landing-page-eLibrary.jpg';

export const assets={
    iitdh_logo,
    footer_image,
    header_image
}

export const category_list=[
    {
        category_name:"Engineering",
    },
    {
        category_name:"Science",
    },
    {
        category_name:"Technology and Applied Sciences",
    },
    {
        category_name:"Competitive Exams and Career Development",
    },
    {
        category_name:"Business and Management",
    },
    {
      category_name:"Programming and Software Development",
  }
]

export const Engineering=[
    {
      department_name:"Computer Science",
    },
    {
      department_name:"Mechanical Engineering",
    },
    {
      department_name:"Electrical Engineering",
    },
    {
      department_name:"Civil Engineering",
    },
    {
      department_name:"Chemical Engineering",
    },
    {
      department_name:"Engineering Physics",
    }
]



export const books_data=[
    {
      "title": "Cosmos",
      "description": "Explore the universe and our place in it.",
      "author": "Carl Sagan",
      "genre": "Popular Science",
      "department": "Physics",
      "count": 15,
      "vendor": "Stellar Books",
      "vendor_id": 1021,
      "publisher": "Random House",
      "publisher_id": 123456,
      "category": "Science"
    },
    {
      "title": "The Elegant Universe",
      "description": "String theory and the nature of reality.",
      "author": "Brian Greene",
      "genre": "Physics",
      "department": "Physics",
      "count": 10,
      "vendor": "Quantum Press",
      "vendor_id": 1022,
      "publisher": "W. W. Norton & Company",
      "publisher_id": 234567,
      "category": "Science"
    },
    {
      "title": "The Feynman Lectures on Physics",
      "description": "Classic lectures on physics by Richard Feynman.",
      "author": "Richard P. Feynman",
      "genre": "Physics",
      "department": "Physics",
      "count": 18,
      "vendor": "Quantum Books",
      "vendor_id": 1027,
      "publisher": "Addison-Wesley",
      "publisher_id": 789012,
      "category": "Science"
    },
    {
      "title": "The Fabric of the Cosmos: Space, Time, and the Texture of Reality",
      "description": "Physics of the universe and its fundamental structure.",
      "author": "Brian Greene",
      "genre": "Physics",
      "department": "Physics",
      "count": 16,
      "vendor": "Quantum Press",
      "vendor_id": 1049,
      "publisher": "Alfred A. Knopf",
      "publisher_id": 234590,
      "category": "Science"
    },
    {
      "title": "Surely You're Joking, Mr. Feynman!",
      "description": "Anecdotes from the life of physicist Richard Feynman.",
      "author": "Richard P. Feynman",
      "genre": "Memoir",
      "department": "Physics",
      "count": 14,
      "vendor": "Quantum Books",
      "vendor_id": 1038,
      "publisher": "W. W. Norton & Company",
      "publisher_id": 901289,
      "category": "Science"
    },
    {
      "title": "Silent Spring",
      "description": "Environmental science and the impact of pesticides.",
      "author": "Rachel Carson",
      "genre": "Environmental Science",
      "department": "Biology",
      "count": 14,
      "vendor": "Green Earth Publishing",
      "vendor_id": 1028,
      "publisher": "Houghton Mifflin",
      "publisher_id": 890123,
      "category": "Science"
    },
    {
      "title": "The Disappearing Spoon: And Other True Tales of Madness, Love, and the History of the World from the Periodic Table of the Elements",
      "description": "Chemistry and its quirky tales.",
      "author": "Sam Kean",
      "genre": "Chemistry",
      "department": "Chemistry",
      "count": 7,
      "vendor": "ChemBooks",
      "vendor_id": 1047,
      "publisher": "Little, Brown and Company",
      "publisher_id": 901278,
      "category": "Science"
    },
    {
      "title": "Genome: The Autobiography of a Species in 23 Chapters",
      "description": "Insights into human genetics and the genome.",
      "author": "Matt Ridley",
      "genre": "Genetics",
      "department": "Biology",
      "count": 12,
      "vendor": "GeneTech Publications",
      "vendor_id": 1024,
      "publisher": "HarperCollins",
      "publisher_id": 456789,
      "category": "Science"
    },
    {
      "title": "The Double Helix",
      "description": "Discovery of the structure of DNA.",
      "author": "James D. Watson",
      "genre": "History of Science",
      "department": "Biology",
      "count": 7,
      "vendor": "Helix Books",
      "vendor_id": 1025,
      "publisher": "Atheneum Publishers",
      "publisher_id": 567890,
      "category": "Science"
    },
    {
      "title": "The Origin of Species",
      "description": "Foundational work on evolutionary biology.",
      "author": "Charles Darwin",
      "genre": "Natural History",
      "department": "Biology",
      "count": 20,
      "vendor": "Naturalist Publications",
      "vendor_id": 1026,
      "publisher": "John Murray",
      "publisher_id": 678901,
      "category": "Science"
    },
    {
      "title": "Gödel, Escher, Bach: An Eternal Golden Braid",
      "description": "Exploration of cognition and self-reference.",
      "author": "Douglas Hofstadter",
      "genre": "Mathematics",
      "department": "Mathematics",
      "count": 11,
      "vendor": "MindBooks",
      "vendor_id": 1029,
      "publisher": "Basic Books",
      "publisher_id": 901234,
      "category": "Science"
    },
    {
      "title": "The Structure of Scientific Revolutions",
      "description": "Philosophy of science and paradigm shifts.",
      "author": "Thomas S. Kuhn",
      "genre": "Philosophy",
      "department": "Mathematics",
      "count": 9,
      "vendor": "Paradigm Press",
      "vendor_id": 1030,
      "publisher": "University of Chicago Press",
      "publisher_id": 123401,
      "category": "Science"
    },
    {
      "title": "The Brain That Changes Itself",
      "description": "Neuroplasticity and the transforming power of our brain.",
      "author": "Norman Doidge",
      "genre": "Neuroscience",
      "department": "Mathematics",
      "count": 16,
      "vendor": "NeuroBooks",
      "vendor_id": 1031,
      "publisher": "Penguin Books",
      "publisher_id": 234512,
      "category": "Science"
    },
    {
      "title": "A Brief History of Time",
      "description": "Overview of modern physics and the universe.",
      "author": "Stephen Hawking",
      "genre": "Physics",
      "department": "Mathematics",
      "count": 12,
      "vendor": "Quantum Press",
      "vendor_id": 1032,
      "publisher": "Bantam Books",
      "publisher_id": 345678,
      "category": "Science"
    },
    {
      "title": "The Selfish Gene",
      "description": "Theory of evolution and the role of genes.",
      "author": "Richard Dawkins",
      "genre": "Evolutionary Biology",
      "department": "Biology",
      "count": 18,
      "vendor": "GeneTech Publications",
      "vendor_id": 1033,
      "publisher": "Oxford University Press",
      "publisher_id": 456712,
      "category": "Science"
    },
    {
      "title": "The Greatest Show on Earth: The Evidence for Evolution",
      "description": "Evidence and mechanisms of evolution.",
      "author": "Richard Dawkins",
      "genre": "Evolutionary Biology",
      "department": "Biology",
      "count": 13,
      "vendor": "BioBooks",
      "vendor_id": 1034,
      "publisher": "Free Press",
      "publisher_id": 567823,
      "category": "Science"
    },
    {
      "title": "The Immortal Life of Henrietta Lacks",
      "description": "The story of the woman whose cells revolutionized medicine.",
      "author": "Rebecca Skloot",
      "genre": "Medical Science",
      "department": "Biology",
      "count": 9,
      "vendor": "BioBooks",
      "vendor_id": 1035,
      "publisher": "Crown Publishing Group",
      "publisher_id": 678934,
      "category": "Science"
    },
    {
      "title": "The Emperor of All Maladies: A Biography of Cancer",
      "description": "A history of cancer and its treatment.",
      "author": "Siddhartha Mukherjee",
      "genre": "Oncology",
      "department": "Biology",
      "count": 7,
      "vendor": "MedBooks",
      "vendor_id": 1036,
      "publisher": "Scribner",
      "publisher_id": 789045,
      "category": "Science"
    },
    {
      "title": "The Sixth Extinction: An Unnatural History",
      "description": "Mass extinctions and their implications for life on Earth.",
      "author": "Elizabeth Kolbert",
      "genre": "Ecology",
      "department": "Biology",
      "count": 6,
      "vendor": "Green Earth Publishing",
      "vendor_id": 1037,
      "publisher": "Henry Holt and Company",
      "publisher_id": 890156,
      "category": "Science"
    },
    {
      "title": "The Gene: An Intimate History",
      "description": "A history of genetics and the human genome.",
      "author": "Siddhartha Mukherjee",
      "genre": "Genetics",
      "department": "Biology",
      "count": 11,
      "vendor": "GeneTech Publications",
      "vendor_id": 1039,
      "publisher": "Scribner",
      "publisher_id": 901267,
      "category": "Science"
    },
    {
      "title": "The Invention of Nature: Alexander von Humboldt's New World",
      "description": "Biography of the scientist who inspired our understanding of nature.",
      "author": "Andrea Wulf",
      "genre": "Biography",
      "department": "Biology",
      "count": 8,
      "vendor": "Naturalist Publications",
      "vendor_id": 1040,
      "publisher": "Alfred A. Knopf",
      "publisher_id": 123423,
      "category": "Science"
    },
    {
      "title": "Lab Girl",
      "description": "A personal journey through the world of plants.",
      "author": "Hope Jahren",
      "genre": "Botany",
      "department": "Biology",
      "count": 9,
      "vendor": "Green Earth Publishing",
      "vendor_id": 1041,
      "publisher": "Alfred A. Knopf",
      "publisher_id": 234534,
      "category": "Science"
    },
    {
      "title": "The Botany of Desire: A Plant's-Eye View of the World",
      "description": "Plants and their evolutionary strategies.",
      "author": "Michael Pollan",
      "genre": "Botany",
      "department": "Biology",
      "count": 10,
      "vendor": "Green Earth Publishing",
      "vendor_id": 1042,
      "publisher": "Random House",
      "publisher_id": 345645,
      "category": "Science"
    },
    {
      "title": "The Princeton Field Guide to Dinosaurs",
      "description": "Comprehensive guide to dinosaurs and their biology.",
      "author": "Gregory S. Paul",
      "genre": "Paleontology",
      "department": "Biology",
      "count": 6,
      "vendor": "DinoBooks",
      "vendor_id": 1043,
      "publisher": "Princeton University Press",
      "publisher_id": 456756,
      "category": "Science"
    },
    {
      "title": "The Sixth Extinction: An Unnatural History",
      "description": "Mass extinctions and their implications for life on Earth.",
      "author": "Elizabeth Kolbert",
      "genre": "Ecology",
      "department": "Biology",
      "count": 6,
      "vendor": "Green Earth Publishing",
      "vendor_id": 1044,
      "publisher": "Henry Holt and Company",
      "publisher_id": 567867,
      "category": "Science"
    },
    {
      "title": "The Gene: An Intimate History",
      "description": "A history of genetics and the human genome.",
      "author": "Siddhartha Mukherjee",
      "genre": "Genetics",
      "department": "Biology",
      "count": 11,
      "vendor": "GeneTech Publications",
      "vendor_id": 1045,
      "publisher": "Scribner",
      "publisher_id": 678978,
      "category": "Science"
    },
    {
      "title": "The Invention of Nature: Alexander von Humboldt's New World",
      "description": "Biography of the scientist who inspired our understanding of nature.",
      "author": "Andrea Wulf",
      "genre": "Biography",
      "department": "Biology",
      "count": 8,
      "vendor": "Naturalist Publications",
      "vendor_id": 1046,
      "publisher": "Alfred A. Knopf",
      "publisher_id": 789089,
      "category": "Science"
    },
      {
        "title": "Clean Code: A Handbook of Agile Software Craftsmanship",
        "description": "Best practices for writing clean and maintainable code.",
        "author": "Robert C. Martin",
        "genre": "Software Development",
        "department": "Information Technology",
        "count": 12,
        "vendor": "CodeBooks",
        "vendor_id": 2001,
        "publisher": "Prentice Hall",
        "publisher_id": 101010,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "The Pragmatic Programmer: Your Journey to Mastery",
        "description": "Guide to becoming a more efficient and effective programmer.",
        "author": "Andrew Hunt, David Thomas",
        "genre": "Software Development",
        "department": "Information Technology",
        "count": 14,
        "vendor": "Pragmatic Press",
        "vendor_id": 2002,
        "publisher": "Addison-Wesley Professional",
        "publisher_id": 202020,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Artificial Intelligence: A Modern Approach",
        "description": "Comprehensive introduction to AI algorithms and techniques.",
        "author": "Stuart Russell, Peter Norvig",
        "genre": "Artificial Intelligence",
        "department": "Artificial Intelligence",
        "count": 15,
        "vendor": "AI Books Ltd.",
        "vendor_id": 2003,
        "publisher": "Pearson",
        "publisher_id": 303030,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Machine Learning Yearning",
        "description": "Practical guide to building machine learning systems.",
        "author": "Andrew Ng",
        "genre": "Machine Learning",
        "department": "Artificial Intelligence",
        "count": 10,
        "vendor": "ML Books",
        "vendor_id": 2004,
        "publisher": "Self-published",
        "publisher_id": 404040,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Data Science for Business: What You Need to Know about Data Mining and Data-Analytic Thinking",
        "description": "Introduction to data science concepts and applications.",
        "author": "Foster Provost, Tom Fawcett",
        "genre": "Data Science",
        "department": "Data Science",
        "count": 12,
        "vendor": "Data Books",
        "vendor_id": 2005,
        "publisher": "O'Reilly Media",
        "publisher_id": 505050,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython",
        "description": "Practical guide to using Python for data analysis tasks.",
        "author": "Wes McKinney",
        "genre": "Data Science",
        "department": "Data Science",
        "count": 13,
        "vendor": "Python Books",
        "vendor_id": 2006,
        "publisher": "O'Reilly Media",
        "publisher_id": 606060,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow",
        "description": "Practical guide to machine learning using popular Python libraries.",
        "author": "Aurélien Géron",
        "genre": "Machine Learning",
        "department": "Artificial Intelligence",
        "count": 12,
        "vendor": "ML Books",
        "vendor_id": 2007,
        "publisher": "O'Reilly Media",
        "publisher_id": 707070,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Deep Learning",
        "description": "Introduction to deep learning methods and applications.",
        "author": "Ian Goodfellow, Yoshua Bengio, Aaron Courville",
        "genre": "Deep Learning",
        "department": "Artificial Intelligence",
        "count": 13,
        "vendor": "DL Books",
        "vendor_id": 2008,
        "publisher": "MIT Press",
        "publisher_id": 808080,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "The Art of Cybersecurity Defense",
        "description": "Strategies and techniques for defending against cyber threats.",
        "author": "Camille Singleton",
        "genre": "Cybersecurity",
        "department": "Cybersecurity",
        "count": 11,
        "vendor": "Cyber Books",
        "vendor_id": 2009,
        "publisher": "McGraw-Hill Education",
        "publisher_id": 909090,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Network Security Essentials",
        "description": "Fundamentals of network security principles and practices.",
        "author": "William Stallings",
        "genre": "Network Security",
        "department": "Cybersecurity",
        "count": 9,
        "vendor": "Secure Books",
        "vendor_id": 2010,
        "publisher": "Pearson",
        "publisher_id": 1010101,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Introduction to Cryptography: Principles and Applications",
        "description": "Introduction to cryptography algorithms and applications.",
        "author": "Johannes Buchmann",
        "genre": "Cryptography",
        "department": "Cybersecurity",
        "count": 10,
        "vendor": "Crypto Books",
        "vendor_id": 2011,
        "publisher": "Springer",
        "publisher_id": 111111,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Hands-On Ethical Hacking and Network Defense",
        "description": "Practical guide to ethical hacking and network defense techniques.",
        "author": "Michael T. Simpson, Kent Backman",
        "genre": "Ethical Hacking",
        "department": "Cybersecurity",
        "count": 10,
        "vendor": "Ethical Books",
        "vendor_id": 2012,
        "publisher": "Cengage Learning",
        "publisher_id": 121212,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "The Phoenix Project: A Novel about IT, DevOps, and Helping Your Business Win",
        "description": "Novel exploring DevOps principles and practices.",
        "author": "Gene Kim, Kevin Behr, George Spafford",
        "genre": "DevOps",
        "department": "Information Technology",
        "count": 10,
        "vendor": "DevOps Books",
        "vendor_id": 2013,
        "publisher": "IT Revolution Press",
        "publisher_id": 131313,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Site Reliability Engineering: How Google Runs Production Systems",
        "description": "Insights into Google's approach to site reliability engineering.",
        "author": "Niall Richard Murphy, Betsy Beyer, Chris Jones, Jennifer Petoff",
        "genre": "Site Reliability Engineering",
        "department": "Information Technology",
        "count": 10,
        "vendor": "SRE Books",
        "vendor_id": 2014,
        "publisher": "O'Reilly Media",
        "publisher_id": 141414,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Practical Data Science with R",
        "description": "Practical guide to data science using R programming language.",
        "author": "Nina Zumel, John Mount",
        "genre": "Data Science",
        "department": "Data Science",
        "count": 12,
        "vendor": "Data Books",
        "vendor_id": 2015,
        "publisher": "Manning Publications",
        "publisher_id": 151515,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Hadoop: The Definitive Guide",
        "description": "Comprehensive guide to Apache Hadoop ecosystem.",
        "author": "Tom White",
        "genre": "Big Data",
        "department": "Data Science",
        "count": 13,
        "vendor": "Big Data Books",
        "vendor_id": 2016,
        "publisher": "O'Reilly Media",
        "publisher_id": 161616,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Cybersecurity Essentials",
        "description": "Fundamentals of cybersecurity principles and practices.",
        "author": "Charles J. Brooks, Christopher Grow",
        "genre": "Cybersecurity",
        "department": "Cybersecurity",
        "count": 12,
        "vendor": "Secure Books",
        "vendor_id": 2017,
        "publisher": "Pearson",
        "publisher_id": 171717,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Machine Learning and Security: Protecting Systems with Data and Algorithms",
        "description": "Intersection of machine learning and cybersecurity.",
        "author": "Clarence Chio, David Freeman",
        "genre": "Machine Learning",
        "department": "Cybersecurity",
        "count": 10,
        "vendor": "ML Books",
        "vendor_id": 2018,
        "publisher": "O'Reilly Media",
        "publisher_id": 181818,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Introduction to the Theory of Computation",
        "description": "Fundamentals of computational theory and complexity.",
        "author": "Michael Sipser",
        "genre": "Theory of Computation",
        "department": "Information Technology",
        "count": 11,
        "vendor": "Comp Theory Books",
        "vendor_id": 2019,
        "publisher": "Cengage Learning",
        "publisher_id": 191919,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Information Systems Today: Managing in the Digital World",
        "description": "Overview of information systems in business and society.",
        "author": "Joseph Valacich, Christoph Schneider, Mark Briggs",
        "genre": "Information Systems",
        "department": "Information Technology",
        "count": 9,
        "vendor": "IS Books",
        "vendor_id": 2020,
        "publisher": "Pearson",
        "publisher_id": 202020,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Hands-On Machine Learning for Cybersecurity",
        "description": "Applying machine learning techniques to cybersecurity challenges.",
        "author": "Soma Halder, Sinan Ozdemir, Clarence Chio",
        "genre": "Machine Learning",
        "department": "Cybersecurity",
        "count": 9,
        "vendor": "ML Books",
        "vendor_id": 2021,
        "publisher": "Packt Publishing",
        "publisher_id": 212121,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Introduction to Machine Learning with Python: A Guide for Data Scientists",
        "description": "Introduction to machine learning using Python programming language.",
        "author": "Andreas C. Müller, Sarah Guido",
        "genre": "Machine Learning",
        "department": "Artificial Intelligence",
        "count": 11,
        "vendor": "ML Books",
        "vendor_id": 2022,
        "publisher": "O'Reilly Media",
        "publisher_id": 222222,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Data Science from Scratch: First Principles with Python",
        "description": "Fundamentals of data science using Python programming language.",
        "author": "Joel Grus",
        "genre": "Data Science",
        "department": "Data Science",
        "count": 10,
        "vendor": "Python Books",
        "vendor_id": 2023,
        "publisher": "O'Reilly Media",
        "publisher_id": 232323,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Cybersecurity: Protecting Critical Infrastructures from Cyber Attack and Cyber Warfare",
        "description": "Strategies for protecting critical infrastructures against cyber threats.",
        "author": "Eric D. Knapp, Raj Samani",
        "genre": "Cybersecurity",
        "department": "Cybersecurity",
        "count": 10,
        "vendor": "Secure Books",
        "vendor_id": 2024,
        "publisher": "Newnes",
        "publisher_id": 242424,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "The Data Warehouse Toolkit: The Definitive Guide to Dimensional Modeling",
        "description": "Comprehensive guide to designing and building data warehouses.",
        "author": "Ralph Kimball, Margy Ross",
        "genre": "Data Warehousing",
        "department": "Data Science",
        "count": 11,
        "vendor": "Data Books",
        "vendor_id": 2025,
        "publisher": "Wiley",
        "publisher_id": 252525,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Hands-On Cybersecurity with Blockchain",
        "description": "Applying blockchain technology to enhance cybersecurity.",
        "author": "Rajneesh Gupta, Nabendu Chaki",
        "genre": "Cybersecurity",
        "department": "Cybersecurity",
        "count": 11,
        "vendor": "Cyber Books",
        "vendor_id": 2026,
        "publisher": "Packt Publishing",
        "publisher_id": 262626,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Information Security: Principles and Practice",
        "description": "Comprehensive coverage of information security principles.",
        "author": "Mark Stamp",
        "genre": "Information Security",
        "department": "Cybersecurity",
        "count": 9,
        "vendor": "Secure Books",
        "vendor_id": 2027,
        "publisher": "Wiley",
        "publisher_id": 272727,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Data Mining: Concepts and Techniques",
        "description": "Fundamentals of data mining concepts and techniques.",
        "author": "Jiawei Han, Micheline Kamber, Jian Pei",
        "genre": "Data Mining",
        "department": "Data Science",
        "count": 9,
        "vendor": "Data Books",
        "vendor_id": 2028,
        "publisher": "Morgan Kaufmann",
        "publisher_id": 282828,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "The Big Data-Driven Business: How to Use Big Data to Win Customers, Beat Competitors, and Boost Profits",
        "description": "Strategies for leveraging big data in business.",
        "author": "Russell Glass, Sean Callahan",
        "genre": "Big Data",
        "department": "Data Science",
        "count": 10,
        "vendor": "Big Data Books",
        "vendor_id": 2029,
        "publisher": "Wiley",
        "publisher_id": 292929,
        "category": "Technology and Applied Sciences"
      },
      {
        "title": "Data Science for Business: What You Need to Know about Data Mining and Data-Analytic Thinking",
        "description": "Introduction to data science concepts and applications.",
        "author": "Foster Provost, Tom Fawcett",
        "genre": "Data Science",
        "department": "Data Science",
        "count": 12,
        "vendor": "Data Books",
        "vendor_id": 2030,
        "publisher": "O'Reilly Media",
        "publisher_id": 303030,
        "category": "Technology and Applied Sciences"
      },
        {
          "title": "Python Crash Course: A Hands-On, Project-Based Introduction to Programming",
          "description": "Introduction to Python programming with practical projects.",
          "author": "Eric Matthes",
          "genre": "Python",
          "department": "Python",
          "count": 15,
          "vendor": "Python Books",
          "vendor_id": 3001,
          "publisher": "No Starch Press",
          "publisher_id": 101010,
          "category": "Programming and Software Development"
        },
        {
          "title": "Automate the Boring Stuff with Python: Practical Programming for Total Beginners",
          "description": "Practical Python projects for automating common tasks.",
          "author": "Al Sweigart",
          "genre": "Python",
          "department": "Python",
          "count": 13,
          "vendor": "Python Books",
          "vendor_id": 3002,
          "publisher": "No Starch Press",
          "publisher_id": 202020,
          "category": "Programming and Software Development"
        },
        {
          "title": "Effective Java",
          "description": "Best practices for Java programming language.",
          "author": "Joshua Bloch",
          "genre": "Java",
          "department": "Java",
          "count": 15,
          "vendor": "Java Books",
          "vendor_id": 3003,
          "publisher": "Addison-Wesley Professional",
          "publisher_id": 303030,
          "category": "Programming and Software Development"
        },
        {
          "title": "Java: The Complete Reference",
          "description": "Comprehensive guide to Java programming language.",
          "author": "Herbert Schildt",
          "genre": "Java",
          "department": "Java",
          "count": 13,
          "vendor": "Java Books",
          "vendor_id": 3004,
          "publisher": "McGraw-Hill Education",
          "publisher_id": 404040,
          "category": "Programming and Software Development"
        },
        {
          "title": "The C Programming Language",
          "description": "Classic book on C programming language.",
          "author": "Brian W. Kernighan, Dennis M. Ritchie",
          "genre": "C/C++",
          "department": "C/C++",
          "count": 15,
          "vendor": "C/C++ Books",
          "vendor_id": 3005,
          "publisher": "Prentice Hall",
          "publisher_id": 505050,
          "category": "Programming and Software Development"
        },
        {
          "title": "C++ Primer",
          "description": "Comprehensive guide to C++ programming language.",
          "author": "Stanley B. Lippman, Josée Lajoie, Barbara E. Moo",
          "genre": "C/C++",
          "department": "C/C++",
          "count": 13,
          "vendor": "C/C++ Books",
          "vendor_id": 3006,
          "publisher": "Addison-Wesley Professional",
          "publisher_id": 606060,
          "category": "Programming and Software Development"
        },
        {
          "title": "JavaScript: The Good Parts",
          "description": "Guide to writing elegant JavaScript code.",
          "author": "Douglas Crockford",
          "genre": "JavaScript",
          "department": "JavaScript",
          "count": 15,
          "vendor": "JavaScript Books",
          "vendor_id": 3007,
          "publisher": "O'Reilly Media",
          "publisher_id": 707070,
          "category": "Programming and Software Development"
        },
        {
          "title": "Eloquent JavaScript: A Modern Introduction to Programming",
          "description": "Introduction to JavaScript programming with focus on modern practices.",
          "author": "Marijn Haverbeke",
          "genre": "JavaScript",
          "department": "JavaScript",
          "count": 13,
          "vendor": "JavaScript Books",
          "vendor_id": 3008,
          "publisher": "No Starch Press",
          "publisher_id": 808080,
          "category": "Programming and Software Development"
        },
        {
          "title": "Python Programming: An Introduction to Computer Science",
          "description": "Introduction to Python programming from a computer science perspective.",
          "author": "John Zelle",
          "genre": "Python",
          "department": "Python",
          "count": 13,
          "vendor": "Python Books",
          "vendor_id": 3009,
          "publisher": "Franklin, Beedle & Associates Inc.",
          "publisher_id": 909090,
          "category": "Programming and Software Development"
        },
        {
          "title": "Head First Java",
          "description": "A learner-friendly guide to Java programming language.",
          "author": "Kathy Sierra, Bert Bates",
          "genre": "Java",
          "department": "Java",
          "count": 15,
          "vendor": "Java Books",
          "vendor_id": 3010,
          "publisher": "O'Reilly Media",
          "publisher_id": 1010101,
          "category": "Programming and Software Development"
        },
        {
          "title": "Java Concurrency in Practice",
          "description": "Guide to writing concurrent and scalable Java applications.",
          "author": "Brian Goetz, Tim Peierls, Joshua Bloch, Joseph Bowbeer, David Holmes, Doug Lea",
          "genre": "Java",
          "department": "Java",
          "count": 13,
          "vendor": "Java Books",
          "vendor_id": 3011,
          "publisher": "Addison-Wesley Professional",
          "publisher_id": 1111111,
          "category": "Programming and Software Development"
        },
        {
          "title": "The C++ Programming Language",
          "description": "Comprehensive guide to C++ programming language.",
          "author": "Bjarne Stroustrup",
          "genre": "C/C++",
          "department": "C/C++",
          "count": 13,
          "vendor": "C/C++ Books",
          "vendor_id": 3012,
          "publisher": "Addison-Wesley Professional",
          "publisher_id": 1212121,
          "category": "Programming and Software Development"
        },
        {
          "title": "Effective Modern C++: 42 Specific Ways to Improve Your Use of C++11 and C++14",
          "description": "Best practices for modern C++ programming.",
          "author": "Scott Meyers",
          "genre": "C/C++",
          "department": "C/C++",
          "count": 15,
          "vendor": "C/C++ Books",
          "vendor_id": 3013,
          "publisher": "O'Reilly Media",
          "publisher_id": 1313131,
          "category": "Programming and Software Development"
        },
        {
          "title": "JavaScript: The Definitive Guide",
          "description": "Comprehensive guide to JavaScript programming language.",
          "author": "David Flanagan",
          "genre": "JavaScript",
          "department": "JavaScript",
          "count": 15,
          "vendor": "JavaScript Books",
          "vendor_id": 3014,
          "publisher": "O'Reilly Media",
          "publisher_id": 1414141,
          "category": "Programming and Software Development"
        },
        {
          "title": "You Don't Know JS: Scope & Closures",
          "description": "In-depth exploration of JavaScript scope and closures.",
          "author": "Kyle Simpson",
          "genre": "JavaScript",
          "department": "JavaScript",
          "count": 13,
          "vendor": "JavaScript Books",
          "vendor_id": 3015,
          "publisher": "O'Reilly Media",
          "publisher_id": 1515151,
          "category": "Programming and Software Development"
        },
        {
          "title": "Python Cookbook: Recipes for Mastering Python 3",
          "description": "Collection of practical Python programming recipes.",
          "author": "David Beazley, Brian K. Jones",
          "genre": "Python",
          "department": "Python",
          "count": 13,
          "vendor": "Python Books",
          "vendor_id": 3016,
          "publisher": "O'Reilly Media",
          "publisher_id": 1616161,
          "category": "Programming and Software Development"
        },
        {
          "title": "Effective Python: 59 Specific Ways to Write Better Python",
          "description": "Best practices for Python programming.",
          "author": "Brett Slatkin",
          "genre": "Python",
          "department": "Python",
          "count": 15,
          "vendor": "Python Books",
          "vendor_id": 3017,
          "publisher": "Addison-Wesley Professional",
          "publisher_id": 1717171,
          "category": "Programming and Software Development"
        },
        {
          "title": "Java 8 in Action: Lambdas, Streams, and Functional-Style Programming",
          "description": "Introduction to functional programming features in Java 8.",
          "author": "Raoul-Gabriel Urma, Mario Fusco, Alan Mycroft",
          "genre": "Java",
          "department": "Java",
          "count": 15,
          "vendor": "Java Books",
          "vendor_id": 3018,
          "publisher": "Manning Publications",
          "publisher_id": 1818181,
          "category": "Programming and Software Development"
        },
        {
          "title": "Head First Python: A Brain-Friendly Guide",
          "description": "Learner-friendly guide to Python programming language.",
          "author": "Paul Barry",
          "genre": "Python",
          "department": "Python",
          "count": 15,
          "vendor": "Python Books",
          "vendor_id": 3019,
          "publisher": "O'Reilly Media",
          "publisher_id": 1919191,
          "category": "Programming and Software Development"
        },
        {
          "title": "Clean Code: A Handbook of Agile Software Craftsmanship",
          "description": "Best practices for writing clean and maintainable code.",
          "author": "Robert C. Martin",
          "genre": "Java",
          "department": "Java",
          "count": 13,
          "vendor": "Java Books",
          "vendor_id": 3020,
          "publisher": "Prentice Hall",
          "publisher_id": 2020202,
          "category": "Programming and Software Development"
        },
        {
          "title": "C Programming Absolute Beginner's Guide",
          "description": "Introduction to C programming for beginners.",
          "author": "Greg Perry, Dean Miller",
          "genre": "C/C++",
          "department": "C/C++",
          "count": 15,
          "vendor": "C/C++ Books",
          "vendor_id": 3021,
          "publisher": "Que Publishing",
          "publisher_id": 2121212,
          "category": "Programming and Software Development"
        },
        {
          "title": "Learning Python",
          "description": "Comprehensive guide to learning Python programming language.",
          "author": "Mark Lutz",
          "genre": "Python",
          "department": "Python",
          "count": 13,
          "vendor": "Python Books",
          "vendor_id": 3022,
          "publisher": "O'Reilly Media",
          "publisher_id": 2222222,
          "category": "Programming and Software Development"
        },
        {
          "title": "Java Performance: The Definitive Guide",
          "description": "Guide to optimizing Java applications for performance.",
          "author": "Scott Oaks",
          "genre": "Java",
          "department": "Java",
          "count": 13,
          "vendor": "Java Books",
          "vendor_id": 3023,
          "publisher": "O'Reilly Media",
          "publisher_id": 2323232,
          "category": "Programming and Software Development"
        },
        {
          "title": "Effective JavaScript: 68 Specific Ways to Harness the Power of JavaScript",
          "description": "Best practices for JavaScript programming.",
          "author": "David Herman",
          "genre": "JavaScript",
          "department": "JavaScript",
          "count": 15,
          "vendor": "JavaScript Books",
          "vendor_id": 3024,
          "publisher": "Addison-Wesley Professional",
          "publisher_id": 2424242,
          "category": "Programming and Software Development"
        },
        {
          "title": "Learning Java",
          "description": "Introduction to Java programming language.",
          "author": "Patrick Niemeyer, Daniel Leuck",
          "genre": "Java",
          "department": "Java",
          "count": 15,
          "vendor": "Java Books",
          "vendor_id": 3025,
          "publisher": "O'Reilly Media",
          "publisher_id": 2525252,
          "category": "Programming and Software Development"
        },
        {
          "title": "JavaScript and JQuery: Interactive Front-End Web Development",
          "description": "Guide to front-end web development using JavaScript and jQuery.",
          "author": "Jon Duckett",
          "genre": "JavaScript",
          "department": "JavaScript",
          "count": 13,
          "vendor": "JavaScript Books",
          "vendor_id": 3026,
          "publisher": "Wiley",
          "publisher_id": 2626262,
          "category": "Programming and Software Development"
        },
        {
          "title": "Head First JavaScript Programming: A Brain-Friendly Guide",
          "description": "Learner-friendly guide to JavaScript programming language.",
          "author": "Eric T. Freeman, Elisabeth Robson",
          "genre": "JavaScript",
          "department": "JavaScript",
          "count": 15,
          "vendor": "JavaScript Books",
          "vendor_id": 3027,
          "publisher": "O'Reilly Media",
          "publisher_id": 2727272,
          "category": "Programming and Software Development"
        },
        {
          "title": "Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython",
          "description": "Guide to data analysis with Python programming language.",
          "author": "Wes McKinney",
          "genre": "Python",
          "department": "Python",
          "count": 15,
          "vendor": "Python Books",
          "vendor_id": 3028,
          "publisher": "O'Reilly Media",
          "publisher_id": 2828282,
          "category": "Programming and Software Development"
        },
        {
          "title": "Java How to Program",
          "description": "Comprehensive guide to Java programming language.",
          "author": "Paul Deitel, Harvey Deitel",
          "genre": "Java",
          "department": "Java",
          "count": 13,
          "vendor": "Java Books",
          "vendor_id": 3029,
          "publisher": "Prentice Hall",
          "publisher_id": 2929292,
          "category": "Programming and Software Development"
        },
        {
          "title": "Learning JavaScript Design Patterns",
          "description": "Guide to design patterns in JavaScript programming language.",
          "author": "Addy Osmani",
          "genre": "JavaScript",
          "department": "JavaScript",
          "count": 13,
          "vendor": "JavaScript Books",
          "vendor_id": 3030,
          "publisher": "O'Reilly Media",
          "publisher_id": 3030303,
          "category": "Programming and Software Development"
        },
          {
            "title": "Principles of Corporate Finance",
            "description": "Fundamental principles of corporate finance.",
            "author": "Richard A. Brealey, Stewart C. Myers, Franklin Allen",
            "genre": "Finance",
            "department": "Finance",
            "count": 8,
            "vendor": "Finance Books",
            "vendor_id": 4001,
            "publisher": "McGraw-Hill Education",
            "publisher_id": 101010,
            "category": "Business and Management"
          },
          {
            "title": "Corporate Finance: A Practical Approach",
            "description": "Practical applications of corporate finance concepts.",
            "author": "Michelle R. Clayman, Martin S. Fridson, George H. Troughton, Matthew Scanlan",
            "genre": "Finance",
            "department": "Finance",
            "count": 7,
            "vendor": "Finance Books",
            "vendor_id": 4002,
            "publisher": "Wiley",
            "publisher_id": 202020,
            "category": "Business and Management"
          },
          {
            "title": "Entrepreneurship: Successfully Launching New Ventures",
            "description": "Guide to entrepreneurship and new venture creation.",
            "author": "Bruce R. Barringer, R. Duane Ireland",
            "genre": "Entrepreneurship",
            "department": "Entrepreneurship",
            "count": 8,
            "vendor": "Entrepreneurship Books",
            "vendor_id": 4003,
            "publisher": "Pearson",
            "publisher_id": 303030,
            "category": "Business and Management"
          },
          {
            "title": "The Lean Startup: How Today's Entrepreneurs Use Continuous Innovation to Create Radically Successful Businesses",
            "description": "Methodology for creating successful startups through continuous innovation.",
            "author": "Eric Ries",
            "genre": "Entrepreneurship",
            "department": "Entrepreneurship",
            "count": 7,
            "vendor": "Entrepreneurship Books",
            "vendor_id": 4004,
            "publisher": "Currency",
            "publisher_id": 404040,
            "category": "Business and Management"
          },
          {
            "title": "Business Analytics: Data Analysis & Decision Making",
            "description": "Applications of business analytics in data-driven decision making.",
            "author": "S. Christian Albright, Wayne L. Winston",
            "genre": "Business Analytics",
            "department": "Business Analytics",
            "count": 8,
            "vendor": "Business Analytics Books",
            "vendor_id": 4005,
            "publisher": "Cengage",
            "publisher_id": 505050,
            "category": "Business and Management"
          },
          {
            "title": "Data Science for Business: What You Need to Know about Data Mining and Data-Analytic Thinking",
            "description": "Introduction to data science applications in business.",
            "author": "Foster Provost, Tom Fawcett",
            "genre": "Business Analytics",
            "department": "Business Analytics",
            "count": 7,
            "vendor": "Business Analytics Books",
            "vendor_id": 4006,
            "publisher": "O'Reilly Media",
            "publisher_id": 606060,
            "category": "Business and Management"
          },
          {
            "title": "Principles of Economics",
            "description": "Fundamental principles of economics.",
            "author": "N. Gregory Mankiw",
            "genre": "Economics",
            "department": "Economics",
            "count": 8,
            "vendor": "Economics Books",
            "vendor_id": 4007,
            "publisher": "Cengage",
            "publisher_id": 707070,
            "category": "Business and Management"
          },
          {
            "title": "Managerial Economics & Business Strategy",
            "description": "Applications of economic theory to managerial decision-making.",
            "author": "Michael Baye, Jeff Prince",
            "genre": "Economics",
            "department": "Economics",
            "count": 7,
            "vendor": "Economics Books",
            "vendor_id": 4008,
            "publisher": "McGraw-Hill Education",
            "publisher_id": 808080,
            "category": "Business and Management"
          },
          {
            "title": "Financial Management: Principles and Applications",
            "description": "Application of financial principles in business management.",
            "author": "Sheridan Titman, Arthur J. Keown, John D. Martin",
            "genre": "Finance",
            "department": "Finance",
            "count": 8,
            "vendor": "Finance Books",
            "vendor_id": 4009,
            "publisher": "Pearson",
            "publisher_id": 909090,
            "category": "Business and Management"
          },
          {
            "title": "Financial Modeling",
            "description": "Guide to financial modeling techniques.",
            "author": "Simon Benninga",
            "genre": "Finance",
            "department": "Finance",
            "count": 7,
            "vendor": "Finance Books",
            "vendor_id": 4010,
            "publisher": "The MIT Press",
            "publisher_id": 1010101,
            "category": "Business and Management"
          },
          {
            "title": "The Art of Startup Fundraising: Pitching Investors, Negotiating the Deal, and Everything Else Entrepreneurs Need to Know",
            "description": "Guide to startup fundraising strategies and techniques.",
            "author": "Alejandro Cremades, Barbara Corcoran",
            "genre": "Entrepreneurship",
            "department": "Entrepreneurship",
            "count": 8,
            "vendor": "Entrepreneurship Books",
            "vendor_id": 4011,
            "publisher": "John Wiley & Sons",
            "publisher_id": 1111111,
            "category": "Business and Management"
          },
          {
            "title": "The Lean Product Playbook: How to Innovate with Minimum Viable Products and Rapid Customer Feedback",
            "description": "Guide to product innovation using lean principles.",
            "author": "Dan Olsen",
            "genre": "Entrepreneurship",
            "department": "Entrepreneurship",
            "count": 7,
            "vendor": "Entrepreneurship Books",
            "vendor_id": 4012,
            "publisher": "Wiley",
            "publisher_id": 1212121,
            "category": "Business and Management"
          },
          {
            "title": "Business Intelligence Guidebook: From Data Integration to Analytics",
            "description": "Comprehensive guide to business intelligence and analytics.",
            "author": "Rick Sherman",
            "genre": "Business Analytics",
            "department": "Business Analytics",
            "count": 8,
            "vendor": "Business Analytics Books",
            "vendor_id": 4013,
            "publisher": "Morgan Kaufmann",
            "publisher_id": 1313131,
            "category": "Business and Management"
          },
          {
            "title": "Predictive Analytics: The Power to Predict Who Will Click, Buy, Lie, or Die",
            "description": "Applications of predictive analytics in business decision-making.",
            "author": "Eric Siegel",
            "genre": "Business Analytics",
            "department": "Business Analytics",
            "count": 7,
            "vendor": "Business Analytics Books",
            "vendor_id": 4014,
            "publisher": "Wiley",
            "publisher_id": 1414141,
            "category": "Business and Management"
          },
          {
            "title": "Principles of Microeconomics",
            "description": "Fundamental principles of microeconomics.",
            "author": "N. Gregory Mankiw",
            "genre": "Economics",
            "department": "Economics",
            "count": 8,
            "vendor": "Economics Books",
            "vendor_id": 4015,
            "publisher": "South-Western College Pub",
            "publisher_id": 1515151,
            "category": "Business and Management"
          },
          {
            "title": "Managerial Economics: Foundations of Business Analysis and Strategy",
            "description": "Foundations of managerial economics and business strategy.",
            "author": "Christopher R. Thomas, S. Charles Maurice",
            "genre": "Economics",
            "department": "Economics",
            "count": 7,
            "vendor": "Economics Books",
            "vendor_id": 4016,
            "publisher": "McGraw-Hill Education",
            "publisher_id": 1616161,
            "category": "Business and Management"
          },
          {
            "title": "Financial Markets and Institutions",
            "description": "Overview of financial markets and institutions.",
            "author": "Anthony Saunders, Marcia Millon Cornett",
            "genre": "Finance",
            "department": "Finance",
            "count": 8,
            "vendor": "Finance Books",
            "vendor_id": 4017,
            "publisher": "McGraw-Hill Education",
            "publisher_id": 1717171,
            "category": "Business and Management"
          },
          {
            "title": "Financial Management: Core Concepts",
            "description": "Core concepts of financial management.",
            "author": "Raymond Brooks",
            "genre": "Finance",
            "department": "Finance",
            "count": 7,
            "vendor": "Finance Books",
            "vendor_id": 4018,
            "publisher": "Pearson",
            "publisher_id": 1818181,
            "category": "Business and Management"
          },
          {
            "title": "Blue Ocean Strategy: How to Create Uncontested Market Space and Make the Competition Irrelevant",
            "description": "Strategic approach to creating uncontested market space.",
            "author": "W. Chan Kim, Renée Mauborgne",
            "genre": "Strategy",
            "department": "Business Analytics",
            "count": 8,
            "vendor": "Business Analytics Books",
            "vendor_id": 4019,
            "publisher": "Harvard Business Review Press",
            "publisher_id": 1919191,
            "category": "Business and Management"
          },
          {
            "title": "Competing on Analytics: The New Science of Winning",
            "description": "Using analytics to gain competitive advantage.",
            "author": "Thomas H. Davenport, Jeanne G. Harris",
            "genre": "Business Analytics",
            "department": "Business Analytics",
            "count": 7,
            "vendor": "Business Analytics Books",
            "vendor_id": 4020,
            "publisher": "Harvard Business Review Press",
            "publisher_id": 2020202,
            "category": "Business and Management"
          },
          {
            "title": "Macroeconomics",
            "description": "Fundamental principles of macroeconomics.",
            "author": "N. Gregory Mankiw",
            "genre": "Economics",
            "department": "Economics",
            "count": 8,
            "vendor": "Economics Books",
            "vendor_id": 4021,
            "publisher": "Worth Publishers",
            "publisher_id": 2121212,
            "category": "Business and Management"
          },
          {
            "title": "Essentials of Economics",
            "description": "Essential concepts in economics.",
            "author": "N. Gregory Mankiw",
            "genre": "Economics",
            "department": "Economics",
            "count": 7,
            "vendor": "Economics Books",
            "vendor_id": 4022,
            "publisher": "Cengage",
            "publisher_id": 2222222,
            "category": "Business and Management"
          },
          {
            "title": "Fundamentals of Financial Management",
            "description": "Fundamental principles of financial management.",
            "author": "Eugene F. Brigham, Joel F. Houston",
            "genre": "Finance",
            "department": "Finance",
            "count": 8,
            "vendor": "Finance Books",
            "vendor_id": 4023,
            "publisher": "Cengage",
            "publisher_id": 2323232,
            "category": "Business and Management"
          },
          {
            "title": "Financial Accounting",
            "description": "Introduction to financial accounting principles.",
            "author": "Robert Libby, Patricia Libby, Daniel Short",
            "genre": "Finance",
            "department": "Finance",
            "count": 7,
            "vendor": "Finance Books",
            "vendor_id": 4024,
            "publisher": "McGraw-Hill Education",
            "publisher_id": 2424242,
            "category": "Business and Management"
          },
          {
            "title": "Essentials of Investments",
            "description": "Essential concepts in investment management.",
            "author": "Zvi Bodie, Alex Kane, Alan J. Marcus",
            "genre": "Finance",
            "department": "Finance",
            "count": 8,
            "vendor": "Finance Books",
            "vendor_id": 4025,
            "publisher": "McGraw-Hill Education",
            "publisher_id": 2525252,
            "category": "Business and Management"
          },
          {
            "title": "Real Estate Finance & Investments",
            "description": "Fundamentals of real estate finance and investments.",
            "author": "William B. Brueggeman, Jeffrey D. Fisher",
            "genre": "Finance",
            "department": "Finance",
            "count": 7,
            "vendor": "Finance Books",
            "vendor_id": 4026,
            "publisher": "McGraw-Hill Education",
            "publisher_id": 2626262,
            "category": "Business and Management"
          },
          {
            "title": "The Four Steps to the Epiphany: Successful Strategies for Startups That Win",
            "description": "Strategies for successful startup development.",
            "author": "Steve Blank",
            "genre": "Entrepreneurship",
            "department": "Entrepreneurship",
            "count": 8,
            "vendor": "Entrepreneurship Books",
            "vendor_id": 4027,
            "publisher": "K&S Ranch",
            "publisher_id": 2727272,
            "category": "Business and Management"
          },
          {
            "title": "Value Proposition Design: How to Create Products and Services Customers Want",
            "description": "Designing value propositions for products and services.",
            "author": "Alexander Osterwalder, Yves Pigneur, Gregory Bernarda, Alan Smith",
            "genre": "Entrepreneurship",
            "department": "Entrepreneurship",
            "count": 7,
            "vendor": "Entrepreneurship Books",
            "vendor_id": 4028,
            "publisher": "Wiley",
            "publisher_id": 2828282,
            "category": "Business and Management"
          },
          {
            "title": "Data Science for Business: What You Need to Know about Data Mining and Data-Analytic Thinking",
            "description": "Introduction to data science applications in business.",
            "author": "Foster Provost, Tom Fawcett",
            "genre": "Business Analytics",
            "department": "Business Analytics",
            "count": 8,
            "vendor": "Business Analytics Books",
            "vendor_id": 4029,
            "publisher": "O'Reilly Media",
            "publisher_id": 2929292,
            "category": "Business and Management"
          },
          {
            "title": "Business Intelligence Guidebook: From Data Integration to Analytics",
            "description": "Comprehensive guide to business intelligence and analytics.",
            "author": "Rick Sherman",
            "genre": "Business Analytics",
            "department": "Business Analytics",
            "count": 7,
            "vendor": "Business Analytics Books",
            "vendor_id": 4030,
            "publisher": "Morgan Kaufmann",
            "publisher_id": 3030303,
            "category": "Business and Management"
          },
            {
              "title": "GATE Guide Mechanical Engineering 2024",
              "description": "Comprehensive guide for GATE Mechanical Engineering preparation.",
              "author": "GKP",
              "genre": "GATE Preparation",
              "department": "GATE Preparation",
              "count": 3,
              "vendor": "GATE Books Co.",
              "vendor_id": 5001,
              "publisher": "Pearson",
              "publisher_id": 101010,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "GRE Prep 2024: Practice Tests + Proven Strategies + Online",
              "description": "Updated GRE preparation book with practice tests and strategies.",
              "author": "Kaplan Test Prep",
              "genre": "GRE Preparation",
              "department": "GRE Preparation",
              "count": 3,
              "vendor": "GRE Books Co.",
              "vendor_id": 5002,
              "publisher": "Kaplan Publishing",
              "publisher_id": 202020,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "Cracking the Coding Interview: 189 Programming Questions and Solutions",
              "description": "Programming interview preparation with coding questions and solutions.",
              "author": "Gayle Laakmann McDowell",
              "genre": "Resume Building and Interview Skills",
              "department": "Resume Building and Interview Skills",
              "count": 3,
              "vendor": "Coding Books Co.",
              "vendor_id": 5003,
              "publisher": "CareerCup",
              "publisher_id": 303030,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "GATE Guide Computer Science and Information Technology 2024",
              "description": "Updated guide for GATE CS & IT preparation with practice questions.",
              "author": "Arihant Experts",
              "genre": "GATE Preparation",
              "department": "GATE Preparation",
              "count": 3,
              "vendor": "GATE Books Co.",
              "vendor_id": 5004,
              "publisher": "Arihant Publications",
              "publisher_id": 404040,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "Official GRE Quantitative Reasoning Practice Questions",
              "description": "GRE quantitative reasoning practice questions for effective preparation.",
              "author": "Educational Testing Service",
              "genre": "GRE Preparation",
              "department": "GRE Preparation",
              "count": 3,
              "vendor": "GRE Books Co.",
              "vendor_id": 5005,
              "publisher": "McGraw-Hill Education",
              "publisher_id": 505050,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "Cracking the PM Interview: How to Land a Product Manager Job in Technology",
              "description": "Guide for product manager job interviews in the tech industry.",
              "author": "Gayle Laakmann McDowell, Jackie Bavaro",
              "genre": "Resume Building and Interview Skills",
              "department": "Resume Building and Interview Skills",
              "count": 3,
              "vendor": "Tech Books Co.",
              "vendor_id": 5006,
              "publisher": "CareerCup",
              "publisher_id": 606060,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "GATE Guide Electrical Engineering 2024",
              "description": "Comprehensive guide for GATE Electrical Engineering preparation.",
              "author": "Made Easy Editorial Board",
              "genre": "GATE Preparation",
              "department": "GATE Preparation",
              "count": 3,
              "vendor": "GATE Books Co.",
              "vendor_id": 5007,
              "publisher": "Made Easy Publications",
              "publisher_id": 707070,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "GRE Prep Plus 2024: Practice Tests + Proven Strategies + Online",
              "description": "Comprehensive GRE preparation with practice tests and strategies.",
              "author": "Kaplan Test Prep",
              "genre": "GRE Preparation",
              "department": "GRE Preparation",
              "count": 3,
              "vendor": "GRE Books Co.",
              "vendor_id": 5008,
              "publisher": "Kaplan Publishing",
              "publisher_id": 808080,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "Case Interview Secrets: A Former McKinsey Interviewer Reveals How to Get Multiple Job Offers in Consulting",
              "description": "Strategies and tips for succeeding in case interviews for consulting jobs.",
              "author": "Victor Cheng",
              "genre": "Resume Building and Interview Skills",
              "department": "Resume Building and Interview Skills",
              "count": 3,
              "vendor": "Consulting Books Co.",
              "vendor_id": 5009,
              "publisher": "Innovative Consulting Press",
              "publisher_id": 909090,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "GATE Guide Civil Engineering 2024",
              "description": "Comprehensive guide for GATE Civil Engineering preparation.",
              "author": "Made Easy Editorial Board",
              "genre": "GATE Preparation",
              "department": "GATE Preparation",
              "count": 3,
              "vendor": "GATE Books Co.",
              "vendor_id": 5010,
              "publisher": "Made Easy Publications",
              "publisher_id": 1010101,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "GRE Math Prep 2024: Review + Practice Tests + Online",
              "description": "Math review and practice tests for GRE preparation.",
              "author": "Kaplan Test Prep",
              "genre": "GRE Preparation",
              "department": "GRE Preparation",
              "count": 3,
              "vendor": "GRE Books Co.",
              "vendor_id": 5011,
              "publisher": "Kaplan Publishing",
              "publisher_id": 1111111,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "Cracking the Coding Interview: 150 Programming Questions and Solutions",
              "description": "Coding interview preparation with solutions to programming questions.",
              "author": "Gayle Laakmann McDowell",
              "genre": "Resume Building and Interview Skills",
              "department": "Resume Building and Interview Skills",
              "count": 3,
              "vendor": "Coding Books Co.",
              "vendor_id": 5012,
              "publisher": "CareerCup",
              "publisher_id": 1212121,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "GATE Guide Electronics and Communication Engineering 2024",
              "description": "Comprehensive guide for GATE Electronics and Communication Engineering preparation.",
              "author": "GKP",
              "genre": "GATE Preparation",
              "department": "GATE Preparation",
              "count": 3,
              "vendor": "GATE Books Co.",
              "vendor_id": 5013,
              "publisher": "Pearson",
              "publisher_id": 1313131,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "Official GRE Verbal Reasoning Practice Questions",
              "description": "GRE verbal reasoning practice questions for effective preparation.",
              "author": "Educational Testing Service",
              "genre": "GRE Preparation",
              "department": "GRE Preparation",
              "count": 3,
              "vendor": "GRE Books Co.",
              "vendor_id": 5014,
              "publisher": "McGraw-Hill Education",
              "publisher_id": 1414141,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "The Google Resume: How to Prepare for a Career and Land a Job at Apple, Microsoft, Google, or Any Top Tech Company",
              "description": "Guide for resume preparation and job applications in tech companies.",
              "author": "Gayle Laakmann McDowell",
              "genre": "Resume Building and Interview Skills",
              "department": "Resume Building and Interview Skills",
              "count": 3,
              "vendor": "Tech Books Co.",
              "vendor_id": 5015,
              "publisher": "CareerCup",
              "publisher_id": 1515151,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "GATE Guide Chemical Engineering 2024",
              "description": "Comprehensive guide for GATE Chemical Engineering preparation.",
              "author": "GKP",
              "genre": "GATE Preparation",
              "department": "GATE Preparation",
              "count": 3,
              "vendor": "GATE Books Co.",
              "vendor_id": 5016,
              "publisher": "Pearson",
              "publisher_id": 1616161,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "GRE Prep 2024: Practice Tests + Proven Strategies + Online",
              "description": "Updated GRE preparation book with practice tests and strategies.",
              "author": "Kaplan Test Prep",
              "genre": "GRE Preparation",
              "department": "GRE Preparation",
              "count": 3,
              "vendor": "GRE Books Co.",
              "vendor_id": 5017,
              "publisher": "Kaplan Publishing",
              "publisher_id": 1717171,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "Designing Your Life: How to Build a Well-Lived, Joyful Life",
              "description": "Strategies for career and life planning.",
              "author": "Bill Burnett, Dave Evans",
              "genre": "Resume Building and Interview Skills",
              "department": "Resume Building and Interview Skills",
              "count": 3,
              "vendor": "Life Design Books Co.",
              "vendor_id": 5018,
              "publisher": "Knopf",
              "publisher_id": 1818181,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "GATE Guide Biotechnology 2024",
              "description": "Comprehensive guide for GATE Biotechnology preparation.",
              "author": "GKP",
              "genre": "GATE Preparation",
              "department": "GATE Preparation",
              "count": 3,
              "vendor": "GATE Books Co.",
              "vendor_id": 5019,
              "publisher": "Pearson",
              "publisher_id": 1919191,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "Official GRE Guide 2024: Review + Practice Tests + Online",
              "description": "Official GRE guide with review, practice tests, and online resources.",
              "author": "Educational Testing Service",
              "genre": "GRE Preparation",
              "department": "GRE Preparation",
              "count": 3,
              "vendor": "GRE Books Co.",
              "vendor_id": 5020,
              "publisher": "McGraw-Hill Education",
              "publisher_id": 2020202,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "GATE Guide Aerospace Engineering 2024",
              "description": "Comprehensive guide for GATE Aerospace Engineering preparation.",
              "author": "GKP",
              "genre": "GATE Preparation",
              "department": "GATE Preparation",
              "count": 3,
              "vendor": "GATE Books Co.",
              "vendor_id": 5021,
              "publisher": "Pearson",
              "publisher_id": 2121212,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "GRE Vocabulary Flashcards 2024: Review + 500 Essential Words + Online",
              "description": "GRE vocabulary flashcards with essential words and online access.",
              "author": "Kaplan Test Prep",
              "genre": "GRE Preparation",
              "department": "GRE Preparation",
              "count": 3,
              "vendor": "GRE Books Co.",
              "vendor_id": 5022,
              "publisher": "Kaplan Publishing",
              "publisher_id": 2222222,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "The Ultimate Scholarship Book 2024: Billions of Dollars in Scholarships, Grants and Prizes",
              "description": "Comprehensive guide to scholarships, grants, and prizes for students.",
              "author": "Gen Tanabe, Kelly Tanabe",
              "genre": "Resume Building and Interview Skills",
              "department": "Resume Building and Interview Skills",
              "count": 3,
              "vendor": "Scholarship Books Co.",
              "vendor_id": 5023,
              "publisher": "SuperCollege",
              "publisher_id": 2323232,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "GATE Guide Instrumentation Engineering 2024",
              "description": "Comprehensive guide for GATE Instrumentation Engineering preparation.",
              "author": "GKP",
              "genre": "GATE Preparation",
              "department": "GATE Preparation",
              "count": 3,
              "vendor": "GATE Books Co.",
              "vendor_id": 5024,
              "publisher": "Pearson",
              "publisher_id": 2424242,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "GRE Verbal Prep 2024: Review + Practice Tests + Online",
              "description": "Verbal review and practice tests for GRE preparation.",
              "author": "Kaplan Test Prep",
              "genre": "GRE Preparation",
              "department": "GRE Preparation",
              "count": 3,
              "vendor": "GRE Books Co.",
              "vendor_id": 5025,
              "publisher": "Kaplan Publishing",
              "publisher_id": 2525252,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "What Color Is Your Parachute? 2024: A Practical Manual for Job-Hunters and Career-Changers",
              "description": "Practical manual for job hunters and career changers.",
              "author": "Richard N. Bolles",
              "genre": "Resume Building and Interview Skills",
              "department": "Resume Building and Interview Skills",
              "count": 3,
              "vendor": "Career Books Co.",
              "vendor_id": 5026,
              "publisher": "Ten Speed Press",
              "publisher_id": 2626262,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "GATE Guide Production and Industrial Engineering 2024",
              "description": "Comprehensive guide for GATE Production and Industrial Engineering preparation.",
              "author": "GKP",
              "genre": "GATE Preparation",
              "department": "GATE Preparation",
              "count": 3,
              "vendor": "GATE Books Co.",
              "vendor_id": 5027,
              "publisher": "Pearson",
              "publisher_id": 2727272,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "GRE Prep 2024: Practice Tests + Proven Strategies + Online",
              "description": "Updated GRE preparation book with practice tests and strategies.",
              "author": "Kaplan Test Prep",
              "genre": "GRE Preparation",
              "department": "GRE Preparation",
              "count": 3,
              "vendor": "GRE Books Co.",
              "vendor_id": 5028,
              "publisher": "Kaplan Publishing",
              "publisher_id": 2828282,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "The Pathfinder: How to Choose or Change Your Career for a Lifetime of Satisfaction and Success",
              "description": "Guide for career choice and change for long-term satisfaction and success.",
              "author": "Nicholas Lore",
              "genre": "Resume Building and Interview Skills",
              "department": "Resume Building and Interview Skills",
              "count": 3,
              "vendor": "Career Books Co.",
              "vendor_id": 5029,
              "publisher": "Touchstone",
              "publisher_id": 2929292,
              "category": "Competitive Exams and Career Development"
            },
            {
              "title": "GATE Guide Architecture and Planning 2024",
              "description": "Comprehensive guide for GATE Architecture and Planning preparation.",
              "author": "GKP",
              "genre": "GATE Preparation",
              "department": "GATE Preparation",
              "count": 3,
              "vendor": "GATE Books Co.",
              "vendor_id": 5030,
              "publisher": "Pearson",
              "publisher_id": 3030303,
              "category": "Competitive Exams and Career Development"
            }          
      
    
]

